grafana:
  enabled: true

  adminPassword: "admin123"

  service:
    type: ClusterIP
    port: 80
    targetPort: 3000

  grafana.ini:
    server:
      root_url: "http://51.250.42.5/grafana/"
      serve_from_sub_path: true

  ingress:
    enabled: true
    ingressClassName: nginx

    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "false"

    hosts: []

    path: /grafana
    pathType: Prefix

    servicePort: 80

  sidecar:
    dashboards:
      enabled: true
      initDelay: 15

    datasources:
      enabled: true
      initDelay: 15

  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m

  securityContext:
    runAsUser: 472
    runAsGroup: 472
    fsGroup: 472

prometheus:
  enabled: true

  prometheusSpec:
    retention: 7d

    resources:
      requests:
        memory: 512Mi
        cpu: 500m
      limits:
        memory: 2Gi
        cpu: 1000m

alertmanager:
  enabled: true

  alertmanagerSpec:
    resources:
      requests:
        memory: 128Mi
        cpu: 100m

prometheus-node-exporter:
  enabled: true

kube-state-metrics:
  enabled: true