apiVersion: apps/v1
kind: Deployment
metadata:
  name: task1-app
  labels:
    app: task1-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task1-app
  template:
    metadata:
      labels:
        app: task1-app
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
      - name: multitool
        image: wbitt/network-multitool
        command: ["sleep", "infinity"] # Гарантируем, что контейнер не завершится