#!/bin/bash
# user-data.sh — выполняется при первом запуске ВМ
# Переменные подставляются из Terraform: ${image_url}

set -e

# Логирование
exec > /var/log/user-data.log 2>&1
echo "=== user-data started at $(date) ==="

# Обновление и установка Apache
apt-get update -qq
apt-get install -y apache2

# Создаём веб-страницу со ссылкой на картинку
cat > /var/www/html/index.html << HTMLEOF
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <title>HW 15.2 - Instance Group + LB</title>
  <style>
    body { font-family: sans-serif; text-align: center; padding: 40px; background: #f5f5f5; }
    .container { background: white; padding: 30px; border-radius: 10px; display: inline-block; }
    img { max-width: 400px; border: 3px solid #2196F3; border-radius: 8px; margin: 20px 0; }
    .meta { color: #666; font-size: 0.9em; margin-top: 20px; }
  </style>
</head>
<body>
  <div class="container">
    <h1>🎉 HW 15.2: Instance Group + Load Balancer</h1>
    <p><strong>Hostname:</strong> $(hostname)</p>
    <p><strong>VM IP:</strong> $(hostname -i)</p>
    
    <h3>Картинка из Object Storage:</h3>
    <img src="${image_url}" alt="Logo" onerror="this.style.display='none';document.getElementById('err').style.display='block'">
    <p id="err" style="display:none;color:red;">❌ Не удалось загрузить картинку</p>
    
    <p><a href="${image_url}" target="_blank">🔗 Открыть картинку</a></p>
  </div>
  <div class="meta">
    Generated by Terraform + user-data | $(date)
  </div>
</body>
</html>
HTMLEOF

# Перезапуск Apache
systemctl restart apache2

# Разрешаем трафик (если включён ufw)
ufw allow 'Apache Full' 2>/dev/null || true

echo "✅ user-data completed at $(date)"