name: Build and Deploy

on:
  push:
    branches: [ main ]
    paths:
      - 'diploma-yandex-project/**'
  workflow_dispatch:

env:
  REGISTRY: cr.yandex
  REPOSITORY_ID: crpnhqbrs0u7vn097bu7
  IMAGE_NAME: my-app
  CLUSTER_ID: catsekbq73ah2rp5dvuv

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install YC CLI
      run: |
        curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
        echo "$HOME/.yandex-cloud/bin" >> $GITHUB_PATH
        echo "$HOME/.yandex-cloud/bin" >> $GITHUB_ENV

    - name: Verify YC CLI
      run: yc --version

    - name: Authorize & Configure Docker
      run: |
        echo "${{ secrets.YC_SERVICE_ACCOUNT_KEY }}" | base64 -d > sa-key.json
        yc config set service-account-key sa-key.json
        yc config set folder-id ${{ secrets.YC_FOLDER_ID }}
        yc cr configure-docker
        rm -f sa-key.json

    - name: Build and Push Image
      run: |
        docker build -t $REGISTRY/$REPOSITORY_ID/$IMAGE_NAME:${{ github.sha }} \
                     -t $REGISTRY/$REPOSITORY_ID/$IMAGE_NAME:latest ./diploma-yandex-project/app
        docker push $REGISTRY/$REPOSITORY_ID/$IMAGE_NAME:${{ github.sha }}
        docker push $REGISTRY/$REPOSITORY_ID/$IMAGE_NAME:latest

    - name: Deploy to Kubernetes
      run: |
        yc managed-kubernetes cluster get-credentials --id ${{ env.CLUSTER_ID }} --external --force
        kubectl apply -f ./diploma-yandex-project/k8s-configs/app/deployment.yaml
        kubectl rollout status deployment/my-app -n app --timeout=300s